---
name: aws_playbook
description: Run RSD aws playbook
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  sudo:
    description: "Run command with sudo"
    type: boolean
    immutable: true
    default: true
  kwarg_op:
    immutable: true
  cwd: "/opt/rsd_aws_env"
  cmd:
    description: "Command to run"
    type: string
    immutable: true
    default: "/opt/stackstorm/virtualenvs/ansible/bin/ansible-playbook {{playbook}} misc/govapps_status.yml"
  playbook:
    description: "Playbook"
    type: string
    required: true
